In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("C:\\SKILL LAB\\MILESTONE 1-CIE\\zomato.csv")

df.head(30)

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
5,5,5,'@99,"Takeaway, Delivery",3.4,37,200.0,No,No,"Mughlai, Biryani, Chinese, North Indian",Whitefield,Whitefield
6,6,6,'@Italy,Casual Dining,4.1,305,700.0,Yes,No,Italian,Banashankari,Kumaraswamy Layout
7,7,7,'@North Parontha Hut,"Takeaway, Delivery",2.8,40,300.0,No,No,North Indian,Indiranagar,Old Airport Road
8,8,8,1000 B.C,Quick Bites,3.2,49,300.0,Yes,No,"Arabian, Sandwich, Rolls, Burger","Byresandra,Tavarekere,Madiwala",Koramangala 5th Block
9,9,9,100ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ°C,Casual Dining,3.7,41,450.0,No,No,"Biryani, North Indian","Byresandra,Tavarekere,Madiwala",BTM
10,10,10,11 to 11 Express Biriyanis,Quick Bites,3.5,22,300.0,Yes,No,"Biryani, Kebab",Electronic City,Electronic City
11,11,11,1131 Bar + Kitchen,"Bar, Casual Dining",4.4,2861,1500.0,No,Yes,"Continental, Asian, Italian, North Indian",Old Airport Road,Indiranagar
12,12,12,12th Main - Grand Mercure,Fine Dining,4.1,353,2000.0,No,Yes,"European, Asian","Byresandra,Tavarekere,Madiwala",Koramangala 3rd Block
13,13,13,1441 Pizzeria,Casual Dining,4.1,119,800.0,Yes,No,"Pizza, Salad",Basavanagudi,JP Nagar
14,14,14,1522 - The Pub,Pub,4.2,1731,1400.0,Yes,No,"Chinese, Continental, North Indian",Malleshwaram,Malleshwaram
15,15,15,154 Breakfast Club,Cafe,4.0,1509,900.0,Yes,Yes,"Cafe, Continental","Byresandra,Tavarekere,Madiwala",Koramangala 3rd Block
16,16,16,1722 Urban Bistro,Casual Dining,4.1,218,600.0,Yes,Yes,"North Indian, Chinese, Fast Food, Biryani","Byresandra,Tavarekere,Madiwala",Koramangala 5th Block
17,17,17,18+ Ice Cafe,Cafe,3.5,24,550.0,No,No,"Cafe, Fast Food, Chinese, Beverages",Kalyan Nagar,Kammanahalli
18,18,18,1947,Casual Dining,3.9,620,1000.0,No,Yes,"North Indian, Chinese, Continental",Rajajinagar,Rajajinagar
19,19,19,1980s Games Cafe,Cafe,3.4,58,400.0,Yes,No,"Cafe, Fast Food",Banashankari,Basavanagudi
20,20,20,1992 Chats - Space,Quick Bites,3.7,33,200.0,Yes,No,Street Food,Malleshwaram,Rajajinagar
21,21,21,1Q1,"Casual Dining, Bar",4.3,595,2500.0,No,Yes,"Asian, Japanese, Thai, Malaysian, Vietnamese, ...",Brigade Road,Infantry Road
22,22,22,1TO3 Kitchen,Delivery,3.1,11,800.0,No,No,"North Indian, Chinese, Continental, Italian, S...",Marathahalli,Marathahalli
23,23,23,2 Statez,Casual Dining,3.7,209,600.0,Yes,No,"Kerala, Seafood, South Indian, North Indian, C...",Kalyan Nagar,Kalyan Nagar
24,24,24,20 Char - Sterlings MAC Hotel,"Casual Dining, Bar",4.0,419,1400.0,Yes,Yes,"Chinese, Continental, North Indian, South Indi...",Indiranagar,Old Airport Road
25,25,25,20 Feet High,"Casual Dining, Bar",4.0,932,1000.0,Yes,Yes,"American, Continental, Steak, Salad",Brigade Road,Church Street
26,26,26,21 C - La Marvella Sarovar Premiere Hotel,Casual Dining,3.6,15,1000.0,No,No,Continental,Basavanagudi,Jayanagar
27,27,27,24 Carats - The Capitol,Casual Dining,3.1,46,1000.0,No,No,"Asian, Continental",Brigade Road,Cunningham Road
28,28,28,24 Hours Cake Delivery,Delivery,3.3,4,700.0,No,No,Bakery,Indiranagar,Old Airport Road
29,29,29,24 Hours Coffee Drop - La Classic,Cafe,3.4,9,800.0,No,No,Cafe,Electronic City,Electronic City

In [6]:
df.tail(10)

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
7095,7095,7095,Zingron,Casual Dining,4.0,510,750.0,Yes,No,"Chinese, Naga","Byresandra,Tavarekere,Madiwala",Koramangala 7th Block
7096,7096,7096,Ziyan's Cafe 27th,Quick Bites,4.0,60,300.0,No,Yes,Kerala,HSR,HSR
7097,7097,7097,Zodiac,Casual Dining,3.6,62,1500.0,No,No,"Italian, Mexican, Mediterranean, North Indian,...",Brookefield,Whitefield
7098,7098,7098,Zodiac - Fortune Select JP Cosmos Hotel,Casual Dining,3.8,91,1800.0,Yes,Yes,"North Indian, South Indian, Chinese, Continental",Brigade Road,Cunningham Road
7099,7099,7099,Zodiac Grills,Quick Bites,3.2,4,500.0,Yes,No,"North Indian, Chinese",HSR,HSR
7100,7100,7100,Zoey's,Cafe,4.3,894,600.0,Yes,No,"Cafe, Italian, Continental, Burger",Bellandur,Sarjapur Road
7101,7101,7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250.0,Yes,No,Desserts,Brigade Road,Church Street
7102,7102,7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350.0,No,No,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,"North Indian, Mughlai, Chinese",Kammanahalli,HBR Layout
7104,7104,7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore

In [7]:
df["restaurant name"]

0                 #FeelTheROLL
1                   #L-81 Cafe
2                      #refuel
3           '@ Biryani Central
4                   '@ The Bbq
                 ...
7100                    Zoey's
7101    ZOROY Luxury Chocolate
7102         Zu's Doner Kebaps
7103                     Zyara
7104                    Zyksha
Name: restaurant name, Length: 7105, dtype: str